# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
require_relative '../../../puppet_x/bsd/hostname_if/carp'

# ---- original file header ----
#
# @summary
#   Summarise what the function does here
#
Puppet::Functions.create_function(:'bsd::get_hostname_if_carp') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    

    config = args.shift

    c = {}
    c[:id]      = config['id']
    c[:device]  = config['device']
    c[:address] = config['address']
    c[:pass]    = config['pass'] if config['pass']
    c[:advbase] = config['advbase'] if config['advbase']
    c[:advskew] = config['advskew'] if config['advskew']

    return HostnameIf::Carp.new(c).content
  
  end
end
