name    'ploperations-bsd'
version '0.0.1'
source 'git://github.com/puppetlabs-operations/puppet-bsd.git'
author 'Puppet labs Operations'
license 'Apache License Version 2.0'
summary 'Manage parts of FreeBSD'
description 'A Puppet module to manage parts BSD'
project_page 'https://github.com/puppetlabs-operations/puppet-bsd'
dependency 'puppetlabs/concat'
dependency 'csail/shell_config'
dependency 'duritong/sysctl'
